
export const FURNITURE_ITEMS = [
  { name: 'ソファ' },
  { name: 'ラグ' },
  { name: 'ダイニングテーブル' },
  { name: 'ダイニングチェア' },
  { name: 'フロアランプ' },
  { name: 'デスクランプ' },
  { name: 'ダウンライト' },
  { name: 'ペンダントライト' },
  { name: 'アート' },
  { name: 'グリーン' },
  { name: '壁紙' },
  { name: 'タイル' },
  { name: 'ミラー' },
  { name: 'クッション' },
  { name: 'デスク' },
  { name: 'ワーキングチェア' },
  { name: 'ベッド' },
  { name: 'テレビボード' },
  { name: 'キャビネット' },
  { name: '壁面収納' },
  { name: '本棚' },
  { name: '食器棚' },
];
